apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  annotations:
    kubernetes.io/change-cause: Hyuk JUn node app ver 1
  namespace: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 2
      maxSurge: 2
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-nginx
        image: nginx
        resources:
          requests:
            cpu: 300m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
         - containerPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-svc-deploy
  namespace: sample
spec:
  type: LoadBalancer
  selector:
    app: nginx
  ports:
    - port: 80
      targetPort: 8080