apiVersion: v1
kind: Pod
metadata:
  name: rs-pod-test
  labels:
    app: web
spec:
  containers:
   - image: c1t1d0s7/myweb
     name: rs-pod1
     ports:
     - containerPort: 8080
       protocol: TCP