apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hj-rs
  labels:
    exp: diff
spec:
  replicas: 3
  selector: #It must match the pod template's labels.
    matchLabels:
      app: ret
  template:
    metadata:
      name: rs-pod-test
      labels:
        app: ret
    spec:
      containers:
      - image: c1t1d0s7/myweb
        name: rs-pod
        ports:
        - containerPort: 8080
          protocol: TCP
