apiVersion: v1
kind: Service
metadata:
  name: hj-clusterip
  labels:
    app: dev
spec:
  selector:
    app: ret
  type: ClusterIP
  ports:
  - port: 80
    protocol: TCP
    targetPort: 8080
    protocol: TCP