apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nam-rs-aff-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nam-rs-aff-front
      tier: frontend
  template:
    metadata:
      labels:
        app: nam-rs-aff-front
        tier: frontend
    spec:
      affinity:
        podAntiAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - frontend
            topologyKey: 'kubernetes.io/hostname'
        podAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
          - labelSelector:
              matchExpressions:
              - key: tier
                operator: In
                values:
                - cache
            topologyKey: 'kubernetes.io/hostname'
      containers:
        - name: namapp
          image: c1t1d0s7/myweb