apiVersion: apps/v1
kind: Deployment
metadata:
  name: wordpress-deploy
spec:
  replicas: 2
  selector:
    matchLabels:
      app: wp
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 2
  minReadySeconds: 20
  template:
    metadata:
      name: nam-pod-wordpress
      labels:
        app: wp
    spec:
      containers:
        - name: nam-con-wordpress
          image: wordpress:latest
          env:
            - name: WORDPRESS_DB_HOST
              value: "mysql-0.mysql"
            - name: WORDPRESS_DB_USER
              value: "wp-admin"
            - name: WORDPRESS_DB_PASSWORD
              value: "1234"
            - name: WORDPRESS_DB_NAME
              value: "wordpress"
          ports:
            - containerPort: 80
          volumeMounts:
            - name: wp-vol
              mountPath: /var/www/html
            - name: ready-config
              mountPath: /var/www/html/ok # 컨피그맵의 이름이 디렉토리로
              subPath: ok # 디렉토리 서브패스
          livenessProbe:
            exec:
              command: ['ls', '/var/www/html/ok']
          readinessProbe:
            httpGet:
              port: 80
              path: /
      volumes:
        - name: wp-vol
          emptyDir: {}
          # persistentVolumeClaim:
          #   claimName: wp-pvc
        - name: ready-config
          configMap:
            name: ok

