apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: wordpress-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: wordpress-deploy
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70
