apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hj-rs-namedport
  labels:
    exp: diff
spec:
  replicas: 3
  selector: #It must match the pod template's labels.
    matchLabels:
      app: ret
  template:
    metadata:
      name: rs-pod-namedport
      labels:
        app: ret
    spec:
      containers:
      - image: c1t1d0s7/myweb
        name: rs-pod-np
        ports:
        - containerPort: 8080
          name: hjport
          protocol: TCP
