apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: nam-hpa
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nam-deploy-hpa
  minReplicas: 1
  maxReplicas: 7
  targetCPUUtilizationPercentage: 70