apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: rs-nfs
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nfs
  template:
    metadata:
      name: nfs-pod
      labels:
        app: nfs
    spec:
      containers:
      - image: nginx
        name: nfs-con
        ports:
          - containerPort: 8080
        volumeMounts:
          - name: nfs-volume
            mountPath:  /usr/share/nginx/html
      volumes:
        - name: nfs-volume
          persistentVolumeClaim:
            claimName: pvc-nfs
       