apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: nam-rs-nf
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nam-rs-nodeaff
  template:
    metadata:
      labels:
        app: nam-rs-nodeaff
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                - key: gpu
                  operator: In
                  values:
                  - highend
                  - midrange
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 10
              preference:
                matchExpressions:
                - key: gpu-model
                  operator: In
                  values:
                  - titan
      containers:
      - name: nam
        image: c1t1d0s7/myweb