apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: nam-ing-tls
spec:
  tls:
    - hosts:
      - mynapp.example.com
      secretName: ingress-tls-secret
  rules:
  - host: mynapp.example.com
    http:
      paths:
        - path: /
          backend:
            serviceName: nam-svc-tls
            servicePort: 80
