apiVersion: apps/v1
kind: Deployment
metadata:
  name: nam-deploy-hpa
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nam-deploy-hpa
  template:
    metadata:
      labels:
        app: nam-deploy-hpa
    spec:
      containers:
      - image: c1t1d0s7/myweb:v1
        name: nam
        resources:
          requests:
            cpu: 50m
            memory: 5Mi
          limits:
            cpu: 100m
            memory: 20Mi
        ports:
          - containerPort: 8080

