apiVersion: v1
kind: Pod
metadata:
  name: sample-pod
spec:
  containers:
    - image: nginx:alpine
      name: sample-pod-con
      volumeMounts:
        - name: azure-disk-vol
          mountPath: /usr/share/nginx/html
  volumes:
    - name: azure-disk-vol
      persistentVolumeClaim:
        claimName: sample-disk-pvc
