apiVersion: v1
kind: Pod
metadata:
  labels:
    purpose: ubuntu-command
  name: ubuntu-command
spec:
  containers:
  - image: ubuntu:focal
    name: ubuntu
    command:
    - "/bin/sh"
    args:
    - "-c"
    - "while true; do echo hello; sleep 10;done"
status: {}
