apiVersion: v1
kind: Pod
metadata:
  name: hj-pod-cm-compress-sub
spec:
  containers:
    - image: nginx
      name: hj-compress-sub
      volumeMounts:
      - name: nginx-compress-config
        mountPath: /etc/nginx/conf.d/nginx-gzip.conf
        subPath: nginx-gzip.conf
      ports:
      - containerPort: 80
  volumes:
    - name: nginx-compress-config
      configMap:
        name: nginx-gzip-config