apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx-deployment
  labels:
    app: nginx
  namespace: sample
spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 1
  minReadySeconds: 20
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: my-nginx
        image: hyukjunacr01.azurecr.io/nginx:latest
        resources:
          requests:
            cpu: 300m
            memory: 200Mi
          limits:
            cpu: 500m
            memory: 500Mi
        ports:
         - containerPort: 80