apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: hyukjun-ingress
spec:
  rules:
  - host: hyukjun.me
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: test
            port: 
              number: 80