apiVersion: apps/v1
kind: ReplicaSet
metadata:
  name: hj-rs-fortune
spec:
  replicas: 1
  selector:
    matchLabels:
      app: hj-rs-fortune
  template:
    metadata:
      labels:
        app: hj-rs-fortune
    spec:
      containers:
        - name: web-server
          image: nginx:alpine
          volumeMounts:
          - name: web-fortune
            mountPath: /usr/share/nginx/html
            readOnly: true
          ports:
            - containerPort: 80
        - name: html-generator
          image: c1t1d0s7/fortune
          volumeMounts:
          - name: web-fortune
            mountPath: /var/htdocs
      volumes:
        - name: web-fortune
          emptyDir: {}
