apiVersion: v1
kind: Pod
metadata:
  name: hj-pod-cm2
spec:
  containers:
    - image:  c1t1d0s7/myweb:customport
      name: hjnapp2
      env:
        - name: NODE_PORT
          valueFrom:
            configMapKeyRef:
              name: hj-config
              key: nodeport
        - name: MESSAGE
          valueFrom:
            configMapKeyRef:
              name: hj-config
              key: message
      args:
      - $(MESSAGE)
      ports:
      - containerPort: 8080
        protocol: TCP